### ISSUE TITLE
EPIC: Judge list

### ISSUE THREAD

**Issue by kostyanf14** [amnis-invictus/ikt.edu.vn.ua#271]
- [x] https://github.com/amnis-invictus/ikt.edu.vn.ua/issues/272
- [x] https://github.com/amnis-invictus/ikt.edu.vn.ua/issues/273
- [x] https://github.com/amnis-invictus/score.judge.ikt.edu.vn.ua/issues/111
- [x] #277
